name: run-nuxt-tests

on:
  push:
  pull_request:

defaults:
  run:
    working-directory: ./examples/nuxt
  uses:
    working-directory: ./examples/nuxt

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "npm"

      - name: Install JavaScript Dependencies
        run: npm install

      - name: Run JavaScript Application
        run: npm run dev &

      - name: Install Composer Dependencies
        working-directory: ./examples/nuxt/browser
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Upgrade Chrome Driver
        working-directory: ./examples/nuxt/browser
        run: php application dusk:chrome-driver `/opt/google/chrome/chrome --version | cut -d " " -f3 | cut -d "." -f1`

      - name: Run Dusk Tests
        working-directory: ./examples/nuxt/browser
        run: php application pest:dusk

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: browser/tests/screenshots

      - name: Upload Console Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: console
          path: browser/tests/console
